function [EEG, status] = conditional_cleanline(EEG, opts)
%CONDITIONAL_CLEANLINE Apply cleanline only above a sampling-rate threshold.
%   [EEG, status] = hbn.conditional_cleanline(EEG, opts) runs pop_cleanline
%   with the reference-pipeline parameters when opts.RunCleanline is true
%   OR EEG.srate >= 500. At 100 Hz sampling the requested line frequencies
%   (typically [60 120 180]) all exceed Nyquist (50 Hz), and the anti-alias
%   filter applied during the 500->100 Hz downsample has already removed
%   them, so the step is a no-op and is skipped.
%
%   status is one of "applied" or "skipped_nyquist".
    arguments
        EEG struct
        opts struct
    end
    runIt = opts.RunCleanline || (EEG.srate >= 500);
    if ~runIt
        status = "skipped_nyquist";
        return;
    end
    EEG = pop_cleanline(EEG, ...
        'bandwidth', 2, ...
        'chanlist', 1:EEG.nbchan, ...
        'computepower', 1, ...
        'linefreqs', opts.LineNoiseHz, ...
        'normSpectrum', 0, ...
        'p', 0.05, ...
        'pad', 2, ...
        'plotfigures', 0, ...
        'scanforlines', 1, ...
        'sigtype', 'Channels', ...
        'tau', 100, ...
        'verb', 1, ...
        'winsize', 4, ...
        'winstep', 1, ...
        'newversion', true);
    status = "applied";
end
