function [EEG, rejected] = reject_bad_channels(EEG, opts)
%REJECT_BAD_CHANNELS Channel-level rejection via pop_clean_rawdata.
%   [EEG, rejected] = hbn.reject_bad_channels(EEG, opts) runs
%   pop_clean_rawdata in channel-rejection-only mode: no ASR, no windowed
%   rejection, no additional high-pass. `rejected` is a string array of
%   channel labels that were removed, derived by diffing chanlocs pre/post.
    arguments
        EEG struct
        opts struct
    end
    before = string({EEG.chanlocs.labels});
    EEG = pop_clean_rawdata(EEG, ...
        'FlatlineCriterion', 'off', ...
        'ChannelCriterion', opts.ChannelCriterion, ...
        'LineNoiseCriterion', opts.LineNoiseCriterion, ...
        'Highpass', 'off', ...
        'BurstCriterion', 'off', ...
        'WindowCriterion', 'off', ...
        'BurstRejection', 'off', ...
        'Distance', 'Euclidian', ...
        'fusechanrej', 1);
    after = string({EEG.chanlocs.labels});
    rejected = setdiff(before, after, 'stable');
end
