function test_write_qa_channels_csv
%TEST_WRITE_QA_CHANNELS_CSV Unit test for the QA CSV writer.
%   Covers: header written on first call, header not repeated on append,
%   multi-entry rejected-channels serialization, NaN-safe numeric cells,
%   CSV escaping when a field contains a comma or a newline, and the
%   status / error_message fields introduced post-review.

    outDir = string(tempname);
    cleaner = onCleanup(@() rmdir_if_exists(outDir)); %#ok<NASGU>
    mkdir(outDir);

    rowOk = struct( ...
        'participant_id', "sub-001", ...
        'status', "ok", ...
        'n_channels_before', 129, ...
        'n_channels_after', 123, ...
        'rejected_channels', ["E7","E15","E48","E67","E80","Cz"], ...
        'srate', 100, ...
        'cleanline_status', "skipped_nyquist", ...
        'duration_s', 15.617, ...
        'error_message', "");
    rowFail = struct( ...
        'participant_id', "sub-002", ...
        'status', "failed_hpf", ...
        'n_channels_before', 129, ...
        'n_channels_after', NaN, ...
        'rejected_channels', "", ...
        'srate', 100, ...
        'cleanline_status', "", ...
        'duration_s', 0.5, ...
        'error_message', "pop_eegfiltnew: malformed input, with a comma");

    csvPath = hbn.write_qa_channels_csv(outDir, rowOk);
    csvPath2 = hbn.write_qa_channels_csv(outDir, rowFail);
    assert(csvPath == csvPath2, "CSV path should be identical on append");

    qa = readtable(csvPath, "TextType","string", "VariableNamingRule","preserve");
    assert(height(qa) == 2, "expected 2 rows, got %d", height(qa));

    % Row 1
    assert(qa.participant_id(1) == "sub-001");
    assert(qa.status(1) == "ok");
    assert(qa.n_channels_before(1) == 129);
    assert(qa.n_channels_after(1) == 123);
    assert(qa.rejected_channels(1) == "E7;E15;E48;E67;E80;Cz");
    assert(qa.cleanline_status(1) == "skipped_nyquist");

    % Row 2 (failure, NaN for n_channels_after, comma-containing error_message)
    assert(qa.participant_id(2) == "sub-002");
    assert(qa.status(2) == "failed_hpf");
    assert(qa.n_channels_before(2) == 129);
    assert(ismissing(qa.n_channels_after(2)), ...
        "n_channels_after should be empty/missing for the failed row");
    assert(qa.error_message(2) == "pop_eegfiltnew: malformed input, with a comma", ...
        "CSV escaping should preserve commas in error_message, got: %s", qa.error_message(2));

    fprintf("test_write_qa_channels_csv: OK\n");
end

function rmdir_if_exists(p)
    if isfolder(p)
        rmdir(p, 's');
    end
end
